FROM conda/miniconda3

RUN conda config --append channels conda-forge
RUN conda update conda --yes
RUN conda update --all --yes
RUN conda install -c anaconda python=3.7

COPY requirements.txt /usr/src/app/

RUN conda create --name interlacer --file /usr/src/app/requirements.txt python=3.7